import type { CodeGenOptions, CodeLanguage, UMLModel } from "@/types/diagram";

export interface GeneratedFile {
  path: string;
  content: string;
}

function cleanIdentifier(name: string): string {
  const sanitized = name.replace(/[^A-Za-z0-9_$]/g, "");
  if (!sanitized) return "_";
  if (/^[0-9]/.test(sanitized)) return `_${sanitized}`;
  return sanitized;
}

function capitalize(name: string): string {
  const clean = cleanIdentifier(name);
  return clean.charAt(0).toUpperCase() + clean.slice(1);
}

function tsType(type: string): string {
  if (type === "unknown") return "unknown";
  const lower = type.toLowerCase();
  if (lower === "string") return "string";
  if (/number|int|long|float|decimal/.test(lower)) return "number";
  if (lower === "boolean" || lower === "bool") return "boolean";
  if (/date|datetime|time/.test(lower)) return "Date";
  if (type.endsWith("[]")) return `${tsType(type.slice(0, -2))}[]`;
  const clean = cleanIdentifier(type.split("|")[0]);
  return clean && clean !== "unknown" ? clean : "string";
}

function javaType(type: string): string {
  if (type === "unknown") return "Object";
  const lower = type.toLowerCase();
  if (lower === "string") return "String";
  if (/^(number|int|long|short)$/.test(lower)) return "long";
  if (/^(float|double|decimal)$/.test(lower)) return "double";
  if (lower === "boolean" || lower === "bool") return "boolean";
  if (/date|datetime|time/.test(lower)) return "java.time.Instant";
  if (type.endsWith("[]")) return `List<${javaType(type.slice(0, -2))}>`;
  return capitalize(type);
}

function pythonType(type: string): string {
  if (type === "unknown") return "Any";
  const lower = type.toLowerCase();
  if (lower === "string") return "str";
  if (/^(number|int|long)$/.test(lower)) return "int";
  if (/^(float|double|decimal)$/.test(lower)) return "float";
  if (lower === "boolean" || lower === "bool") return "bool";
  if (/date|datetime|time/.test(lower)) return "datetime.datetime";
  if (type.endsWith("[]")) return `list[${pythonType(type.slice(0, -2))}]`;
  return cleanIdentifier(type.split("|")[0]) || "Any";
}

function csType(type: string): string {
  if (type === "unknown") return "object";
  const lower = type.toLowerCase();
  if (lower === "string") return "string";
  if (/^(number|int|long)$/.test(lower)) return "long";
  if (/^(float|double|decimal)$/.test(lower)) return "double";
  if (lower === "boolean" || lower === "bool") return "bool";
  if (/date|datetime|time/.test(lower)) return "DateTime";
  if (type.endsWith("[]")) return `IList<${csType(type.slice(0, -2))}>`;
  return capitalize(cleanIdentifier(type.split("|")[0])) || "object";
}

export function generateCode(model: UMLModel, language: CodeLanguage, options: CodeGenOptions): GeneratedFile[] {
  switch (language) {
    case "typescript":
      return generateTypescript(model);
    case "java":
      return generateJava(model, options);
    case "python":
      return generatePython(model, options);
    case "csharp":
      return generateCSharp(model);
  }
}

function classModifiers(cls: UMLModel["classes"][number], model: UMLModel) {
  const parent = model.links.find((l) => l.to === cls.id && l.type === "inheritance");
  const implemented = model.links.filter((l) => l.to === cls.id && l.type === "implementation").map((l) => capitalize(cleanIdentifier(l.from)));
  return { parent, implemented };
}

function classAnalysis(cls: UMLModel["classes"][number], model: UMLModel) {
  return classModifiers(cls, model);
}

function generateTypescript(model: UMLModel): GeneratedFile[] {
  const lines: string[] = ["// Generated by ArchVision AI", ""];
  for (const cls of model.classes) {
    const name = cleanIdentifier(cls.name);
    if (cls.isInterface) {
      lines.push(`export interface ${name} {`);
      for (const attr of cls.attributes) {
        lines.push(`  ${lowercaseMember(attr.name)}${attr.type !== "unknown" ? `: ${tsType(attr.type)}` : ""};`);
      }
      for (const method of cls.methods) {
        const params = method.parameters.map((p) => `${lowercaseMember(p.name)}${p.type ? `: ${tsType(p.type)}` : ""}`).join(", ");
        lines.push(`  ${lowercaseMember(method.name)}(${params}): ${method.returnType === "void" ? "void" : tsType(method.returnType)};`);
      }
      lines.push("}", "");
      continue;
    }
    const { parent, implemented } = classAnalysis(cls, model);
    const abstractKw = cls.isAbstract ? "abstract " : "";
    const parentExt = parent ? ` extends ${cleanIdentifier(parent.from)}` : "";
    const implClause = implemented.length ? ` implements ${implemented.join(", ")}` : "";
    lines.push(`export ${abstractKw}class ${name}${parentExt}${implClause} {`);
    for (const attr of cls.attributes) {
      const mod = attr.visibility === "private" ? "private " : attr.visibility === "protected" ? "protected " : "";
      const readonly = attr.isStatic ? "static readonly " : "";
      lines.push(`  ${mod}${readonly}${lowercaseMember(attr.name)}${attr.type !== "unknown" ? `: ${tsType(attr.type)}` : ""};`);
    }
    for (const method of cls.methods) {
      const params = method.parameters.map((p) => `${lowercaseMember(p.name)}${p.type ? `: ${tsType(p.type)}` : ""}`).join(", ");
      const prefix = method.isAbstract ? "abstract " : method.isStatic ? "static " : "";
      lines.push(`  ${prefix}${lowercaseMember(method.name)}(${params}): ${method.returnType === "void" ? "void" : tsType(method.returnType)} {`);
      lines.push(method.returnType === "void" ? "    // TODO: implement" : '    throw new Error("Not implemented");');
      lines.push("  }");
    }
    lines.push("}", "");
  }
  return [{ path: "models.ts", content: lines.join("\n") }];
}

function generateJava(model: UMLModel, options: CodeGenOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  for (const cls of model.classes) {
    const name = capitalize(cleanIdentifier(cls.name));
    const lines: string[] = ["// Generated by ArchVision AI", ""];
    const { parent, implemented } = classAnalysis(cls, model);
    if (cls.isInterface) {
      lines.push(`public interface ${name} {`);
      for (const method of cls.methods) {
        const params = method.parameters.map((p) => `${javaType(p.type)} ${lowercaseMember(p.name)}`).join(", ");
        lines.push(`    ${javaType(method.returnType)} ${lowercaseMember(method.name)}(${params});`);
      }
      lines.push("}", "");
      files.push({ path: `${name}.java`, content: lines.join("\n") });
      continue;
    }
    const header = cls.isAbstract ? "public abstract class" : "public class";
    const parentClause = parent ? ` extends ${capitalize(cleanIdentifier(parent.from))}` : "";
    const implClause = implemented.length ? ` implements ${implemented.join(", ")}` : "";
    lines.push(`${header} ${name}${parentClause}${implClause} {`);
    for (const attr of cls.attributes) {
      lines.push(`    private ${javaType(attr.type)} ${lowercaseMember(attr.name)};`);
    }
    if (options.includeGettersSetters && !options.useLombok) {
      for (const attr of cls.attributes) {
        lines.push(`    public ${javaType(attr.type)} get${capitalize(attr.name)}() { return ${lowercaseMember(attr.name)}; }`);
        lines.push(`    public void set${capitalize(attr.name)}(${javaType(attr.type)} ${lowercaseMember(attr.name)}) { this.${lowercaseMember(attr.name)} = ${lowercaseMember(attr.name)}; }`);
      }
    }
    for (const method of cls.methods) {
      const params = method.parameters.map((p) => `${javaType(p.type)} ${lowercaseMember(p.name)}`).join(", ");
      lines.push(`    public ${javaType(method.returnType)} ${lowercaseMember(method.name)}(${params}) {`);
      lines.push(method.returnType === "void" ? "        // TODO: implement" : "        return null;");
      lines.push("    }");
    }
    lines.push("}", "");
    files.push({ path: `${name}.java`, content: lines.join("\n") });
  }
  if (options.useLombok && files.length > 0) {
    files.forEach((f) => {
      f.content = `import lombok.Data;\n${f.content}`;
    });
  }
  return files;
}

function generatePython(model: UMLModel, options: CodeGenOptions): GeneratedFile[] {
  const lines: string[] = ["# Generated by ArchVision AI", ""];
  if (options.usePydantic) {
    lines.push("from datetime import datetime", "from pydantic import BaseModel, Field", "");
  } else {
    lines.push("from abc import ABC, abstractmethod", "from datetime import datetime", "");
  }
  for (const cls of model.classes) {
    const name = cleanIdentifier(cls.name);
    const { parent } = classAnalysis(cls, model);
    if (cls.isInterface) {
      if (options.usePydantic) {
        lines.push(`class ${name}(BaseModel):`);
        lines.push("    pass");
      } else {
        lines.push(`class ${name}(ABC):`);
        for (const method of cls.methods) {
          const params = method.parameters.map((p) => `${cleanIdentifier(p.name)}: ${pythonType(p.type)}`).join(", ");
          lines.push(`    @abstractmethod`, `    def ${cleanIdentifier(method.name)}(${params}) -> ${pythonType(method.returnType)}:`, "        ...", "");
        }
        if (cls.methods.length === 0) lines.push("    pass");
        lines.push("");
      }
      lines.push("");
      continue;
    }
    if (options.usePydantic) {
      lines.push(`class ${name}(${parent ? cleanIdentifier(parent.from) : "BaseModel"}):`);
      if (cls.attributes.length === 0) {
        lines.push("    pass");
      } else {
        for (const attr of cls.attributes) {
          lines.push(`    ${cleanIdentifier(attr.name)}: ${pythonType(attr.type)}`);
        }
        for (const method of cls.methods) {
          const params = method.parameters.map((p) => `${cleanIdentifier(p.name)}: ${pythonType(p.type)}`).join(", ");
          lines.push("", `    def ${cleanIdentifier(method.name)}(${params}) -> ${pythonType(method.returnType)}:`);
          lines.push('        """TODO: implement"""');
          lines.push(method.returnType === "void" ? "        pass" : "        raise NotImplementedError");
        }
      }
    } else {
      lines.push(`class ${name}(${parent ? cleanIdentifier(parent.from) : "object"}):`);
      if (cls.attributes.length === 0) {
        lines.push("    pass");
      } else {
        const params = ["self", ...cls.attributes.map((a) => `${cleanIdentifier(a.name)}: ${pythonType(a.type)}=None`)].join(", ");
        lines.push(`    def __init__(${params}):`);
        for (const attr of cls.attributes) {
          lines.push(`        self.${cleanIdentifier(attr.name)} = ${cleanIdentifier(attr.name)}`);
        }
      }
      for (const method of cls.methods) {
        const params = method.parameters.map((p) => `${cleanIdentifier(p.name)}: ${pythonType(p.type)}`).join(", ");
        lines.push("", `    def ${cleanIdentifier(method.name)}(self${params ? `, ${params}` : ""}) -> ${pythonType(method.returnType)}:`);
        lines.push('        """..."""');
        lines.push(method.returnType === "void" ? "        pass" : "        raise NotImplementedError");
      }
      lines.push("");
    }
    lines.push("");
  }
  return [{ path: "models.py", content: lines.join("\n") }];
}

function generateCSharp(model: UMLModel): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  for (const cls of model.classes) {
    const name = capitalize(cleanIdentifier(cls.name));
    const { parent, implemented } = classAnalysis(cls, model);
    const lines: string[] = ["// Generated by ArchVision AI", "", "namespace ArchVision.Model;", ""];
    if (cls.isInterface) {
      lines.push(`public interface ${name} {`);
      for (const method of cls.methods) {
        const params = method.parameters.map((p) => `${csType(p.type)} ${lowercaseMember(p.name)}`).join(", ");
        lines.push(`    ${csType(method.returnType)} ${lowercaseMember(method.name)}(${params});`);
      }
      lines.push("}", "");
    } else {
      const baseClauses = [
        ...(parent ? [capitalize(cleanIdentifier(parent.from))] : []),
        ...implemented.map((i) => capitalize(cleanIdentifier(i))),
      ];
      const headerBase = baseClauses.length ? ` : ${baseClauses.join(", ")}` : "";
      lines.push(`public ${cls.isAbstract ? "abstract " : ""}class ${name}${headerBase} {`);
      for (const attr of cls.attributes) {
        if (!parent || !cls.attributes.some((a) => a.name === attr.name)) {
          const vis = attr.visibility === "private" ? "private" : attr.visibility === "protected" ? "protected" : "public";
          lines.push(`    ${vis} ${csType(attr.type)} ${capitalize(cleanIdentifier(attr.name))} { get; set; }`);
        }
      }
      for (const method of cls.methods) {
        const params = method.parameters.map((p) => `${csType(p.type)} ${lowercaseMember(p.name)}`).join(", ");
        lines.push(`    public ${csType(method.returnType)} ${lowercaseMember(method.name)}(${params}) {`);
        lines.push(method.returnType === "void" ? "        // TODO: implement" : "        throw new NotImplementedException();");
        lines.push("    }");
      }
      lines.push("}", "");
    }
    files.push({ path: `${name}.cs`, content: lines.join("\n") });
  }
  return files;
}

function lowercaseMember(name: string): string {
  if (name === "class") return "_class";
  if (name === "interface") return "_interface";
  if (name === "import") return "_import";
  if (name === "from") return "_from";
  const clean = cleanIdentifier(name);
  return clean.charAt(0).toLowerCase() + clean.slice(1);
}